# Generated by Django 4.2 on 2023-05-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0002_class_subject_classsubject_teacher_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.teacher'),
        ),
    ]
