# Generated by Django 4.2 on 2023-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0003_alter_classsubject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_subjects',
            field=models.ManyToManyField(blank=True, through='Tutor.ClassSubject', to='Tutor.subject'),
        ),
    ]
