# Generated by Django 4.2 on 2023-05-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0004_alter_teacher_class_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_subjects',
        ),
    ]
