# Generated by Django 4.2 on 2023-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0005_remove_teacher_class_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_subjects',
            field=models.ManyToManyField(blank=True, through='Tutor.ClassSubject', to='Tutor.subject'),
        ),
    ]
