# Generated by Django 4.2 on 2023-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0008_remove_teacher_class_subjects_remove_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
    ]
