# Generated by Django 4.2 on 2023-05-31 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0010_alter_student_address_alter_student_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=100)),
                ('parents_number', models.CharField(max_length=100)),
                ('students_name', models.CharField(max_length=100)),
                ('students_number', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, null=True)),
                ('address', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('preffered_teaching_location', models.CharField(choices=[('Student Home', 'Student Home'), ('Tutor Place', 'Tutor Place'), ('Both', 'Both')], max_length=100)),
                ('teaching_time', models.CharField(max_length=100)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('confirmation', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.teacher')),
            ],
        ),
    ]
