# Generated by Django 4.2 on 2023-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0011_remove_student_address_remove_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='preffered_teaching_location',
            field=models.CharField(blank=True, choices=[('Student Home', 'Student Home'), ('Tutor Place', 'Tutor Place'), ('Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='subjects',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='teaching_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
