# Generated by Django 4.2 on 2023-06-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0012_alter_enrollmentform_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.student'),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.teacher'),
        ),
    ]
