# Generated by Django 4.2 on 2023-06-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0013_alter_enrollmentform_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
