# Generated by Django 4.2 on 2023-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0014_alter_teacher_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, choices=[('Secondary level', 'Secondary level'), ('Higher Secondary level(Pursuing)', 'Higher Secondary level(Pursuing)'), ('Higher Secondary level(Completed)', 'Higher Secondary level(Completed)'), ('Bachelors Degree(Pursuing)', 'Bachelors Secondary level(Pursuing)'), ('Bachelors Degree(Completed)', 'Bachelors Degree(Completed)'), ('Masters Degree(Pursuing)', 'Masters Degree(Pusuing)'), ('Masters Degree(Completed)', 'Masters Degree(Completed)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_experience',
            field=models.CharField(blank=True, choices=[('Not Yet', 'Not Yet'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('9 Years', '9 Years'), ('10 Years', '10 Years'), ('10+ Years', '10+ Years')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_location',
            field=models.CharField(blank=True, choices=[('Student Home', 'Student Home'), ('Tutor Place', 'Tutor Place'), ('Both', 'Both')], max_length=100, null=True),
        ),
    ]
