# Generated by Django 4.2 on 2023-06-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0015_remove_teacher_class_name_teacher_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
