# Generated by Django 4.2 on 2023-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0017_alter_enrollmentform_gender_alter_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
