# Generated by Django 4.2 on 2023-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0019_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
