# Generated by Django 4.2 on 2023-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0020_enrollmentform_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='cancelledDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentform',
            name='confirmedDate',
            field=models.DateTimeField(default=None),
        ),
    ]
