# Generated by Django 4.2 on 2023-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0021_enrollmentform_cancelleddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='selected_tuitionjoining_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
