# Generated by Django 4.2 on 2023-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0022_enrollmentform_selected_tuitionjoining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentform',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
