# Generated by Django 4.2 on 2023-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0023_enrollmentform_endtime_enrollmentform_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='confirmedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
