# Generated by Django 4.2 on 2023-06-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0025_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
