# Generated by Django 4.2 on 2023-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0026_timeslot_disable_timeslot_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='finishedTeachingDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
