# Generated by Django 4.2 on 2023-06-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0027_enrollmentform_finishedteachingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
