# Generated by Django 4.2 on 2023-06-29 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0028_teacher_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
