# Generated by Django 4.2 on 2023-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0029_teacher_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
