# Generated by Django 4.2 on 2023-07-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0034_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=64, unique=True)),
                ('pw_reset_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_reset_user', to='Tutor.teacher')),
            ],
            options={
                'verbose_name_plural': 'ResetPassword',
            },
        ),
    ]
