# Generated by Django 4.2 on 2023-07-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Tutor', '0035_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('code', models.CharField(default=None, max_length=64, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'ResetPasswordVerify',
            },
        ),
    ]
