# Generated by Django 4.2 on 2023-07-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0037_student_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentform',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentform',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
