# Generated by Django 4.2 on 2023-07-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0038_enrollmentform_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
