# Generated by Django 4.2 on 2023-07-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0039_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='preview_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
