# Generated by Django 4.2 on 2023-08-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0040_teacher_preview_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='preview_certificateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Teacher_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.teacher')),
            ],
        ),
    ]
