# Generated by Django 4.2 on 2023-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0041_teacher_preview_certificatedate_teacher_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_notification',
            name='previewCertificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_notification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
