# Generated by Django 4.2 on 2023-08-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Tutor', '0043_student_gender_student_name_student_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('code', models.CharField(default=None, max_length=64, unique=True)),
                ('new_password', models.CharField(max_length=128)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'ChangePasswordVerify',
            },
        ),
    ]
