# Generated by Django 4.2 on 2023-08-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0044_changepasswordverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
