# Generated by Django 4.2 on 2023-08-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0046_student_latitude_student_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='teacher',
        ),
        migrations.CreateModel(
            name='TeacherClassSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.classsubject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.teacher')),
            ],
        ),
    ]
