# Generated by Django 4.2 on 2023-08-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0047_remove_classsubject_teacher_teacherclasssubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.classsubject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.teacher')),
            ],
        ),
    ]
