# Generated by Django 4.2 on 2023-08-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0048_teacherclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherClassSubjects',
        ),
    ]
